"""create programme and cours tables

Revision ID: be3dc257758a
Revises: 
Create Date: 2025-11-22 20:21:30.167104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3dc257758a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codeProgramme', sa.String(length=20), nullable=False),
    sa.Column('nomProgramme', sa.String(length=255), nullable=False),
    sa.Column('descProgramme', sa.Text(), nullable=True),
    sa.Column('publicCible', sa.Text(), nullable=True),
    sa.Column('dureeProgramme', sa.Interval(), nullable=True),
    sa.Column('dateCreation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prixProgramme', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DISPONIBLE', 'NON_DISPONIBLE', 'REFUSE', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_codeProgramme'), 'programmes', ['codeProgramme'], unique=True)
    op.create_index(op.f('ix_programmes_id'), 'programmes', ['id'], unique=False)
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codeCours', sa.String(length=20), nullable=False),
    sa.Column('titreCours', sa.String(length=255), nullable=False),
    sa.Column('prixCours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dateCreation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_codeCours'), 'cours', ['codeCours'], unique=True)
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_codeCours'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_programmes_id'), table_name='programmes')
    op.drop_index(op.f('ix_programmes_codeProgramme'), table_name='programmes')
    op.drop_table('programmes')
    # ### end Alembic commands ###
