"""Ajout de frais_admission

Revision ID: 5c3eb4844169
Revises: e035a3d7c405
Create Date: 2025-11-26 06:50:26.251103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3eb4844169'
down_revision: Union[str, Sequence[str], None] = 'e035a3d7c405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('frais_admission', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admissions', 'frais_admission')
    # ### end Alembic commands ###
