"""create admissions table

Revision ID: c7eec0cb03dc
Revises: 
Create Date: 2025-11-25 13:10:52.155050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7eec0cb03dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_admission', sa.Enum('PROGRAMME', 'COURS', name='type_admission_enum'), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('cours_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'ACCEPTEE', 'REFUSEE', 'ANNULEE', name='statut_admission_enum'), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_demande', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_maj', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admissions_cours_id'), 'admissions', ['cours_id'], unique=False)
    op.create_index(op.f('ix_admissions_id'), 'admissions', ['id'], unique=False)
    op.create_index(op.f('ix_admissions_programme_id'), 'admissions', ['programme_id'], unique=False)
    op.create_index(op.f('ix_admissions_user_id'), 'admissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admissions_user_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_programme_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_cours_id'), table_name='admissions')
    op.drop_table('admissions')
    # ### end Alembic commands ###
